### ISSUE TITLE
Exception ticking world | Incompatibility with Let's Do! Beach Party & MCA?

### ISSUE THREAD

**Issue by Lolfaceftw** [SolipIngen/minecraft.sassot#55]
After a certain while loading the world, the server will crash with the following crash report:
[crash-2023-08-18_13.38.01-server.txt](https://github.com/SolipIngen/minecraft.sassot/files/12380061/crash-2023-08-18_13.38.01-server.txt)
[crash-2023-08-18_13.49.40-server.txt](https://github.com/SolipIngen/minecraft.sassot/files/12380063/crash-2023-08-18_13.49.40-server.txt)
[crash-2023-08-18_13.11.30-server.txt](https://github.com/SolipIngen/minecraft.sassot/files/12380064/crash-2023-08-18_13.11.30-server.txt)

> Stacktrace:
	at solipingen.sassot.village.ModVillagerProfessions$TypeAwareSellForOneEmeraldFactory.lambda$new$1(ModVillagerProfessions.java:211)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at solipingen.sassot.village.ModVillagerProfessions$TypeAwareSellForOneEmeraldFactory.<init>(ModVillagerProfessions.java:210)
	at solipingen.sassot.village.ModVillagerProfessions.replaceFishermanProfessionToLeveledTrade(ModVillagerProfessions.java:89)
	at net.minecraft.class_1646.localvar$dfl001$sassot$modifiedFilledRecipes(class_1646.java:4974)
	at net.minecraft.class_1646.method_7237(class_1646.java:886)
	at net.minecraft.class_3988.method_8264(class_3988.java:115)
	at fabric.net.mca.server.SpawnQueue.tick(SpawnQueue.java:50)
	at fabric.net.mca.server.world.data.VillageManager.tick(VillageManager.java:173)
	at fabric.net.mca.fabric.MCAFabric.lambda$onInitialize$0(MCAFabric.java:50)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:63)
	at net.minecraft.class_3218.handler$bje000$fabric-lifecycle-events-v1$endWorldTick(class_3218.java:9240)
	at net.minecraft.class_3218.method_18765(class_3218.java:396)

Three mods I seem to find in the crash report: MCA, Let's Do Beach Party, and Sassot. No crashes have happened until Sassot was installed.

EDIT: It seems to have incompatibility with mods that modify villager behavior

**Comment by Lolfaceftw** [comment]
Okay, I give up, it seems it has incompatibilities with any mod that modifies villager behavior, removed MCA and Let's Do Beach Party and still same error appears but with a different villager type id from another mod

**Comment by Lolfaceftw** [comment]
hey, sorry for this bump, but is there any update regarding this?

**Comment by SolipIngen** [comment]
Thank you for writing in, and apologies for the late response.
The next update will attempt to address this alongside other fixes/changes. Please wait a little as this may take some (hopefully not much) time.

**Comment by Lolfaceftw** [comment]
Thank you, soliplngen. Additionally, this [crash report](https://mclo.gs/42h8rmt) from Let's Do: Meadow might help you too. It's a similar error.

I find that these crashes often occur when I am traveling over a beach (might want to test out Let's Do Beach Party's Beaches too) near the ocean.

**Comment by Lolfaceftw** [comment]
As of now, with MCA installed, I seem to not encounter any issues, maybe it's an incompatibility from the Let's Do series (specifically their villagers)? I suspected MCA since it has been tagged in the crash report but Let's Do Meadow was still there.

**Comment by makumaku1974** [comment]
I have MCA too it seems to crash the same as yours

**Comment by SolipIngen** [comment]
Apologies to all for the significant delay.
Both versions of v1.1.3.a-1.20.1 should have resolved this issue. Please let me know if the Issue persists, I will leave this Issue open for a few days.
